baseurl = "/"
title = "Browse Theme"
languageCode = "en-us"
# this example loads the theme as hugo module
# comment out line below, and uncomment the line after it if you prefer to load the theme normally
theme = "github.com/mawngo/browse"
# theme = "browse" # comment this out if you'ld rather use a fork of this repo or use it as a git submodule
disqusShortname = ""

[services]
[services.googleAnalytics]
ID = "G-MEASUREMENT_ID" # Enable Google Analytics by entering your tracking id

[services.disqus]
shortname = '' # Enable comments by entering your Disqus shortname

[pagination]
pagerSize = 10