description = "John Doe's Personal blog about everything" # Description of your site
opengraph = true
twitter_cards = false
readmore = false # Show "Read more" button in list if true
pager = true
post_meta = ["date", "categories"] # Order of post meta information
mainSections = ["post", "docs"]
defaultLightingMode = "auto" # other possible values: "dark", "light"
iconsDir = "img/" #defaults to "icons/"

authorbox = true

[author]
  name = "John Doe"
  bio = "John Doe's true identity is unknown. Maybe he is a successful blogger or writer. Nobody knows it."
  avatar = "img/avatar.png"

[logo]
subtitle = "Just another site" # Logo subtitle

[sidebar]
home = "right"   # Configure layout for home page
list = "right"   # Configure layout for list pages
single = "right" # Configure layout for single pages
# Enable widgets in given order
widgets = ["search", "recent", "categories", "taglist"]

[widgets]
recent_num = 5 # Set the number of articles in the "Recent articles" widget
tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
[matomo_analytics]
enable = false # To enable matomo analytics change to `true`.
websiteDomain = "example.com" # Set the domain name of your website, in most cases same as your base URL this is required.
matomoDomain = "matomo.example.com" # Set to Matomo domain
matomoSiteID = "1" # Default is set to 1, change this to the siteid being tracked
